version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - postgres
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - postgres
      - mongodb

  postgres:
    build: ./containers/postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ~/.meme:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    container_name: mongodb
    build: ./containers/mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mongodb_data:
  backend_node:
  frontend_node:
